#!/bin/bash

. $(dirname $0)/gyi

install end.sh err.sh fpid.sh local_profile.sh _temp_path.sh temp_path.sh yk_support.sh /lib/yk_support_for_sh
ln -s /lib/yk_support_for_sh/yk_support.sh /etc/shrc.d
