#!/bin/env bash

. gy_support


install end.sh err.sh fpid.sh local_profile.sh _temp_path.sh temp_path.sh /usr/local/lib/yk_support_for_sh
install yk_support.sh /usr/local/etc/shrc.d

#install_lines /etc/skel/.zshrc <<END
install_lines .zshrc .bashrc <<END
    for i in /usr/local/etc/shrc.d/*.sh; do
        if [ "\$i" = "/usr/local/etc/shrc.d/*.sh" ]; then
            break
        fi
        if [ -r "\$i" ]; then
            . "\$i"
        fi
    done
    unset i
END
